print("Hello World!")
name = input("Enter your name: ")
print("--------------------------------------------------\n")
print(f"************* {name} *****************************\n")
print("--------------------------------------------------\n")
age = int(input("Enter your age: "))
print("My name is {} and I am {} years old".format(name, age))
